# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mistake_arr.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import PyQt5.sip
import PyQt5

class CommonHelper:
    def __init__(self):
        pass

    @staticmethod
    def readQss(style):
        with open(style, 'r',encoding="utf-8") as f:
            return f.read()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(490, 456)
        styleFile = './mistake_arr.qss'
        qssStyle = CommonHelper.readQss(styleFile)
        Form.setStyleSheet(qssStyle)
        Form.setWindowTitle("图片排版器")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 471, 431))
        self.groupBox.setObjectName("groupBox")
        self.input_btn = QtWidgets.QPushButton(self.groupBox)
        self.input_btn.setGeometry(QtCore.QRect(360, 40, 75, 23))
        self.input_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.input_btn.setDefault(False)
        self.input_btn.setObjectName("input_btn")
        self.output_btn = QtWidgets.QPushButton(self.groupBox)
        self.output_btn.setGeometry(QtCore.QRect(360, 90, 75, 23))
        self.output_btn.setObjectName("output_btn")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setGeometry(QtCore.QRect(70, 120, 62, 22))
        self.doubleSpinBox.setValue(11.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.grayLabel = QtWidgets.QLabel(self.groupBox)
        self.grayLabel.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.grayLabel.setObjectName("grayLabel")
        self.grayLabel_2 = QtWidgets.QLabel(self.groupBox)
        self.grayLabel_2.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.grayLabel_2.setObjectName("grayLabel_2")
        self.grayLabel_3 = QtWidgets.QLabel(self.groupBox)
        self.grayLabel_3.setGeometry(QtCore.QRect(10, 120, 54, 12))
        self.grayLabel_3.setObjectName("grayLabel_3")
        self.grayLabel_4 = QtWidgets.QLabel(self.groupBox)
        self.grayLabel_4.setGeometry(QtCore.QRect(160, 120, 54, 12))
        self.grayLabel_4.setObjectName("grayLabel_4")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(220, 120, 62, 22))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_2.setValue(11.0)
        self.grayLabel_6 = QtWidgets.QLabel(self.groupBox)
        self.grayLabel_6.setGeometry(QtCore.QRect(10, 160, 54, 12))
        self.grayLabel_6.setObjectName("grayLabel_6")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(70, 160, 62, 22))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_3.setValue(11.0)
        self.grayLabel_5 = QtWidgets.QLabel(self.groupBox)
        self.grayLabel_5.setGeometry(QtCore.QRect(160, 160, 54, 12))
        self.grayLabel_5.setObjectName("grayLabel_5")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(220, 160, 62, 22))
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_4.setValue(11.0)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(70, 200, 211, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setValue(2)
        self.grayLabel_7 = QtWidgets.QLabel(self.groupBox)
        self.grayLabel_7.setGeometry(QtCore.QRect(10, 200, 54, 12))
        self.grayLabel_7.setObjectName("grayLabel_7")
        self.input_box = QtWidgets.QLineEdit(self.groupBox)
        self.input_box.setGeometry(QtCore.QRect(10, 40, 341, 20))
        self.input_box.setObjectName("input_box")
        self.output_box = QtWidgets.QLineEdit(self.groupBox)
        self.output_box.setGeometry(QtCore.QRect(10, 90, 341, 20))
        self.output_box.setObjectName("output_box")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(70, 240, 211, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.grayLabel_8 = QtWidgets.QLabel(self.groupBox)
        self.grayLabel_8.setGeometry(QtCore.QRect(10, 240, 54, 12))
        self.grayLabel_8.setObjectName("grayLabel_8")
        self.submit_btn = QtWidgets.QPushButton(self.groupBox)
        self.submit_btn.setGeometry(QtCore.QRect(10, 290, 421, 31))
        self.submit_btn.setObjectName("submit_btn")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(10, 380, 421, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 360, 54, 12))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Form)
        self.input_btn.clicked.connect(Form.inputSelect)
        self.output_btn.clicked.connect(Form.outputSelect)
        self.submit_btn.clicked.connect(Form.start)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "基本信息"))
        self.input_btn.setText(_translate("Form", "选择文件"))
        self.output_btn.setText(_translate("Form", "选择路径"))
        self.grayLabel.setText(_translate("Form", "输入文件"))
        self.grayLabel_2.setText(_translate("Form", "输出文件夹"))
        self.grayLabel_3.setText(_translate("Form", "左边距（mm）"))
        self.grayLabel_4.setText(_translate("Form", "右边距（mm）"))
        self.grayLabel_6.setText(_translate("Form", "上边距（mm）"))
        self.grayLabel_5.setText(_translate("Form", "下边距（mm）"))
        self.grayLabel_7.setText(_translate("Form", "分列"))
        self.comboBox.setItemText(0, _translate("Form", "A4|210*297"))
        self.comboBox.setItemText(1, _translate("Form", "16开|185*260"))
        self.grayLabel_8.setText(_translate("Form", "纸张规格"))
        self.submit_btn.setText(_translate("Form", "点击开始"))
        self.label_9.setText(_translate("Form", "运行状态"))
